substitutions:
  friendly_name: "laundrylight2"
  friendlyname: "laundrylight2"
  deviceicon: "mdi:light-recessed"

esphome:
  name: laundrylight2

bk72xx:
  board: generic-bk7231t-qfn32-tuya

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret failback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password
ota:
  password: !secret ota_password
sensor:
  - platform: wifi_signal
    name: ${friendlyname} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${friendlyname} Uptime

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendlyname} IP
    ssid:
      name: ${friendlyname} SSID
    bssid:
      name: ${friendlyname} BSSID
    mac_address:
      name: ${friendlyname} Mac

## ---------------- ##
##    Status LED    ##
## ---------------- ##
status_led:
  pin:
    number: P1
    inverted: true

## ---------------- ##
##      Relays      ##
## ---------------- ##
output:
  # Relay 1
  - platform: gpio
    id: relay_1
    pin: P8
  # Relay 2
  - platform: gpio
    id: relay_2
    pin: P26  
  # Relay 3
  - platform: gpio
    id: relay_3
    pin: P24

## ------------ ##
##    Lights    ##
## ------------ ##
light:
  # Light 1
  - platform: binary
    name: west_light
    icon: ${deviceicon}
    output: relay_1
    id: light_1

  # Light 2
  - platform: binary
    name: laundry_fan
    icon: mdi:ceiling-fan
    output: relay_2
    id: light_2

   # Light 3
  - platform: binary
    name: laundry_light
    icon: ${deviceicon}
    output: relay_3
    id: light_3

## ----------------- ##
##      Buttons      ##
## ----------------- ##
binary_sensor:
  # Button 1
  - platform: gpio
    id: button_1
    pin:
      number: P14
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: light_1
    internal: True

  # Button 2
  - platform: gpio
    id: button_2
    pin:
      number: P9
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: light_2
    internal: True

    # Button 3
  - platform: gpio
    id: button_3
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: light_3
    internal: True
