substitutions:
  friendly_name: "LetterBox"

esphome:
  name: letterbox
  platform: ESP32
  board: esp32thing

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
   static_ip: 172.22.22.10
   gateway: 172.22.22.1
   subnet: 255.255.255.0
   dns1: 172.22.22.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret failback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: !secret ota_password


mqtt:
  broker: 192.168.22.13
  discovery: True
  discovery_retain: True
  topic_prefix: LetterBoxESP
  will_message:

ota:
  password: !secret ota_password

sensor:
 - platform: wifi_signal
   name: “esp32_1 WiFi Signal Sensor”
   #   update_interval: s
# - platform: adc
#   pin: A0
#   attenuation: 11db
#   name: batery
   
binary_sensor:
 - platform: gpio
   id: beem
   pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: True

   device_class: occupancy
   name: LetterBoxMail

deep_sleep:
  run_duration: 1s
  sleep_duration: 720min
  wakeup_pin: GPIO27
  wakeup_pin_mode: INVERT_WAKEUP
