substitutions:
    friendly_name: "Power Point Switch"

esphome:
  name: powerpointswitch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret failback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

status_led:
  pin:
    number: GPIO4
    inverted: True

output:
  # Top (or only) button
  - platform: gpio
    pin: GPIO13
    id: relay1

  # Bottom button (for Smart Double Switch - delete for single switch)
  - platform: gpio
    pin: GPIO14
    id: relay2

switch:
  # Top (or only) button
  - platform: output
    name: "${friendly_name} Left"
    output: relay1
    id: switch1

  # Bottom button (for Smart Double Switch - delete for single switch)
  - platform: output
    name: "${friendly_name} Right"
    output: relay2
    id: switch2
  - platform: restart
    name: "${friendly_name} Switch REBOOT"

# Buttons
binary_sensor:
  # Top (or only) button
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Left Button"
    #toggle relay on push
    on_press:
      - switch.toggle: switch1

  # Bottom button (for Smart Double Switch - delete for single switch)
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Right Button"
    #toggle relay on push
    on_press:
      - switch.toggle: switch2

