substitutions:
    friendly_name: "Washing Machine Switch"

esphome:
  name: washingmachineswitch
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret failback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Washing Machine Switch Power Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Washing Machine Switch Power Status"

switch:
  - platform: gpio
    id: green_led
    pin:
      number: GPIO13
      inverted: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Washing Machine Switch"
    pin: GPIO14
    id: relay
    icon: mdi:television
    restore_mode: ALWAYS_OFF

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: "Washing Machine Current"
      unit_of_measurement: A
    voltage:
      name: "Washing Machine Voltage"
      unit_of_measurement: V
    power:
      id: washing_machine_wattage
      name: "Washing Maching Power"
      unit_of_measurement: W
    current_resistor: "0.00087"   ### HIGHER VALUE GIVES LOWER WATTAGE
    voltage_divider: "2030"   ### LOWER VALUE GIVES LOWER VOLTAGE
    change_mode_every: 8
    update_interval: 5s

  - platform: total_daily_energy
    name: "Washing Machine Daily Energy"
    power_id: washing_machine_wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

time:
  - platform: homeassistant
    id: homeassistant_time
