substitutions:
  friendly_name: "Washing Machine Power"
  friendlyname: ${friendly_name}
  deviceicon: "mdi:washing-machine"

esphome:
  name: "washerpower"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret failback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password


#################################

ota:
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: ${friendlyname} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${friendlyname} Uptime
  - platform: cse7766
    current:
      name: "${friendlyname} Current"
      icon: mdi:current-ac
      filters:
        - multiply: 4.867
        - throttle_average: 30s
    voltage:
      name: "${friendlyname} Voltage"
      icon: mdi:flash
      filters:
        - multiply: 1.905
        - throttle_average: 30s
    power:
      name: "${friendlyname} Power"
      icon: mdi:gauge
      id: powerpoint_wattage
      filters:
        - throttle_average: 30s
    energy:
      name: "${friendlyname} Energy"
      icon: mdi:gauge
      id: powerpoint_energy
      filters:
        - throttle: 30s
  - platform: total_daily_energy
    name: "${friendlyname} Daily Energy"
    power_id: powerpoint_wattage
    filters:
      - multiply: 0.001
      - throttle: 60s
    unit_of_measurement: kWh
    icon: mdi:chart-bar

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendlyname} IP
    ssid:
      name: ${friendlyname} SSID
    bssid:
      name: ${friendlyname} BSSID
    mac_address:
      name: ${friendlyname} Mac
  - platform: version
    name: ${friendlyname} ESPHome Version

# Enable time component for use by daily power sensor
time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  rx_pin: P10
  baud_rate: 4800

output:
- platform: gpio
  pin: P8
  inverted: false
  id: led

###Buttons
binary_sensor:
# Left button
  - platform: gpio
    device_class: power
    pin:
      number: P7
      mode: INPUT
      inverted: True
    name: "${friendlyname} Left Button"
    #toggle relay on push
    on_press:
      - switch.toggle: relay_a
# Right button
  - platform: gpio
    device_class: power
    pin:
      number: P24
      mode: INPUT
      inverted: True
    name: "${friendlyname} Right Button"
    #toggle relay on push
    on_press:
      - switch.toggle: relay_b

switch:
  - platform: gpio
    pin: P6
    name: "${friendlyname}_left"
    restore_mode: always on
    id: relay_a
    icon: mdi:washing-machine
  - platform: gpio
    pin: P26
    name: "${friendlyname}_right"
    restore_mode: always off
    id: relay_b
    icon: mdi:power-socket-au
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led
